version: '3.9'

services:
  web:
    container_name: blog-nginx
    image: nginx:latest
    ports:
      - '8060:80'
    volumes:
      - ./project:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - blog
  php-fpm:
    container_name: blog-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./project:/var/www/html
    networks:
      - blog
networks:
  blog:
    driver: bridge